import {Button} from "std-widgets.slint";
export component MainWindow inherits Window {
    in-out property<string> clock-text: "12：24";
    in-out property<string> digit1-text: "2";
    in-out property<bool> digit1-visible: true;
    in-out property<string> digit10-text: "1";
    in-out property<bool> digit10-visible: true;
    in-out property<bool> footer-visible: false;
    in-out property<bool> good-bye-visible: false;
    in-out property<bool> header-visible: false;
    in-out property<bool> parking-slot-visible: false;
    in-out property<bool> payment-visible: false;
    in-out property<bool> welcome-visible: true;
    callback accept-clicked <=> accept.clicked;
    callback cancel-clicked <=> cancel.clicked;
    callback card-clicked <=> card.clicked;
    callback cash-clicked <=> cash.clicked;
    callback good-bye-clicked <=> good-bye.clicked;
    callback ic-clicked <=> ic.clicked;
    callback key-0-clicked <=> key-0.clicked;
    callback key-1-clicked <=> key-1.clicked;
    callback key-2-clicked <=> key-2.clicked;
    callback key-3-clicked <=> key-3.clicked;
    callback key-4-clicked <=> key-4.clicked;
    callback key-5-clicked <=> key-5.clicked;
    callback key-6-clicked <=> key-6.clicked;
    callback key-7-clicked <=> key-7.clicked;
    callback key-8-clicked <=> key-8.clicked;
    callback key-9-clicked <=> key-9.clicked;
    callback key-c-clicked <=> key-c.clicked;
    callback pay-clicked <=> pay.clicked;
    callback welcome-clicked <=> welcome.clicked;
    height: 600px;
    title: "";
    width: 1024px;
    x: 0px;
    y: 0px;
    Rectangle {
        height: 602px;
        width: 1027px;
        x: -1px;
        y: -1px;
        Rectangle {
            background: #f5f5ed;
            height: 600px;
            width: 1024px;
            x: 1px;
            y: 1px;
        }
    }
    footer := Rectangle {
        visible: root.footer-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            height: 65px;
            width: 1027px;
            x: -1px;
            y: 537px;
            Rectangle {
                background: #e9f1ff;
                height: 62px;
                width: 1024px;
                x: 1px;
                y: 2px;
            }
        }
    }
    good-bye := TouchArea {
        visible: root.good-bye-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 43px;
                font-weight: 700;
                height: 62px;
                horizontal-alignment: center;
                text: "ご利用ありがとうございました";
                vertical-alignment: center;
                width: 781px;
                x: 120px;
                y: 239px;
            }
            Rectangle {
                height: 6px;
                width: 684px;
                x: 170px;
                y: 316px;
                Rectangle {
                    background: #183e77;
                    height: 2px;
                    width: 680px;
                    x: 1px;
                    y: 2px;
                }
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 29px;
                font-weight: 700;
                height: 84px;
                horizontal-alignment: center;
                text: "精算後5分で再びロック板が上がりますので\n５分以内に出庫してください";
                vertical-alignment: center;
                width: 771px;
                x: 128px;
                y: 354px;
            }
        }
    }
    payment := Rectangle {
        visible: root.payment-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            height: 83px;
            width: 628px;
            x: 225px;
            y: 99px;
            Rectangle {
                background: #ffffff;
                height: 80px;
                width: 625px;
                x: 1px;
                y: 2px;
            }
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 35px;
            font-weight: 700;
            height: 51px;
            horizontal-alignment: left;
            text: "料金は";
            vertical-alignment: center;
            width: 141px;
            x: 63px;
            y: 126px;
        }
        amount := Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 49px;
            font-weight: 700;
            height: 71px;
            horizontal-alignment: left;
            text: "200";
            vertical-alignment: center;
            visible: true;
            width: 123px;
            x: 477px;
            y: 103px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 27px;
            font-weight: 700;
            height: 39px;
            horizontal-alignment: left;
            text: "円";
            vertical-alignment: center;
            width: 35px;
            x: 783px;
            y: 137px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 35px;
            font-weight: 700;
            height: 51px;
            horizontal-alignment: left;
            text: "です";
            vertical-alignment: center;
            width: 91px;
            x: 873px;
            y: 126px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 28px;
            font-weight: 700;
            height: 40px;
            horizontal-alignment: left;
            text: "お支払方法をお選びください";
            vertical-alignment: center;
            width: 492px;
            x: 266px;
            y: 223px;
        }
        cash := Button {
            height: 91px;
            primary: true;
            text: "現金";
            width: 403px;
            x: 97px;
            y: 293px;
        }
        card := Button {
            height: 91px;
            primary: true;
            text: "クレジットカード";
            width: 403px;
            x: 522px;
            y: 293px;
        }
        ic := Button {
            height: 91px;
            primary: true;
            text: "交通系IC";
            width: 403px;
            x: 97px;
            y: 401px;
        }
        pay := Button {
            height: 91px;
            primary: true;
            text: "電子マネー";
            width: 403px;
            x: 522px;
            y: 401px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 25px;
            font-weight: 700;
            height: 36px;
            horizontal-alignment: left;
            text: "サービス券は先に入れてください";
            vertical-alignment: center;
            width: 498px;
            x: 264px;
            y: 551px;
        }
    }
    parking-slot := Rectangle {
        visible: root.parking-slot-visible;
        x: 0px;
        y: 0px;
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 35px;
            font-weight: 700;
            height: 51px;
            horizontal-alignment: center;
            text: "駐車位置番号を入力してください";
            vertical-alignment: center;
            width: 695px;
            x: 165px;
            y: 113px;
        }
        key-1 := Button {
            height: 50px;
            text: "1";
            width: 113px;
            x: 552px;
            y: 204px;
        }
        key-2 := Button {
            height: 50px;
            text: "2";
            width: 113px;
            x: 680px;
            y: 204px;
        }
        key-3 := Button {
            height: 50px;
            text: "3";
            width: 113px;
            x: 810px;
            y: 204px;
        }
        key-4 := Button {
            height: 49px;
            text: "4";
            width: 113px;
            x: 552px;
            y: 266px;
        }
        key-5 := Button {
            height: 49px;
            text: "5";
            width: 113px;
            x: 680px;
            y: 266px;
        }
        key-6 := Button {
            height: 49px;
            text: "6";
            width: 113px;
            x: 810px;
            y: 266px;
        }
        key-7 := Button {
            height: 48px;
            text: "7";
            width: 113px;
            x: 552px;
            y: 329px;
        }
        key-8 := Button {
            height: 48px;
            text: "8";
            width: 113px;
            x: 680px;
            y: 329px;
        }
        key-9 := Button {
            height: 48px;
            text: "9";
            width: 113px;
            x: 810px;
            y: 329px;
        }
        key-0 := Button {
            height: 50px;
            text: "0";
            width: 113px;
            x: 680px;
            y: 390px;
        }
        key-c := Button {
            height: 50px;
            text: "クリア";
            width: 113px;
            x: 810px;
            y: 390px;
        }
        Rectangle {
            height: 232px;
            width: 458px;
            x: 55px;
            y: 206px;
            Rectangle {
                background: #ffffff;
                border-color: #6f6f6f;
                border-radius: 26px;
                border-width: 6px;
                height: 230px;
                width: 456px;
                x: 1px;
                y: 1px;
            }
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 24px;
            height: 35px;
            horizontal-alignment: center;
            text: "NO.";
            vertical-alignment: center;
            width: 60px;
            x: 137px;
            y: 327px;
        }
        Rectangle {
            height: 90px;
            width: 91px;
            x: 224px;
            y: 277px;
            Rectangle {
                background: #ffffff;
                border-color: #000000;
                border-width: 1px;
                height: 87px;
                width: 87px;
                x: 2px;
                y: 1px;
            }
        }
        digit10 := Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 46px;
            height: 66px;
            horizontal-alignment: center;
            text: root.digit10-text;
            vertical-alignment: center;
            visible: root.digit10-visible;
            width: 33px;
            x: 252px;
            y: 286px;
        }
        Rectangle {
            height: 90px;
            width: 91px;
            x: 339px;
            y: 277px;
            Rectangle {
                background: #ffffff;
                border-color: #000000;
                border-width: 1px;
                height: 87px;
                width: 87px;
                x: 2px;
                y: 1px;
            }
        }
        digit1 := Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 46px;
            height: 66px;
            horizontal-alignment: center;
            text: root.digit1-text;
            vertical-alignment: center;
            visible: root.digit1-visible;
            width: 33px;
            x: 369px;
            y: 286px;
        }
        accept := Button {
            height: 50px;
            primary: true;
            text: "確定▶";
            width: 458px;
            x: 55px;
            y: 459px;
        }
    }
    header := Rectangle {
        visible: root.header-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            height: 156px;
            width: 1133px;
            x: -73px;
            y: -78px;
            Rectangle {
                background: #183e77;
                height: 154px;
                width: 1129px;
                x: 1px;
                y: 1px;
            }
        }
        cancel := Button {
            height: 50px;
            text: "トップに戻る";
            width: 164px;
            x: 40px;
            y: 13px;
        }
        Button {
            height: 50px;
            text: "English";
            width: 164px;
            x: 820px;
            y: 13px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 17px;
            height: 25px;
            horizontal-alignment: center;
            text: "English";
            vertical-alignment: center;
            width: 84px;
            x: 859px;
            y: 24px;
        }
        clock := Text {
            color: #ffffff;
            font-family: "Source Han Sans";
            font-size: 30px;
            font-weight: 700;
            height: 44px;
            horizontal-alignment: center;
            text: root.clock-text;
            vertical-alignment: center;
            visible: true;
            width: 128px;
            x: 640px;
            y: 14px;
        }
    }
    welcome := TouchArea {
        visible: root.welcome-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            Rectangle {
                height: 157px;
                width: 945px;
                x: 40px;
                y: 31px;
                Rectangle {
                    background: #183e77;
                    height: 154px;
                    width: 942px;
                    x: 1px;
                    y: 1px;
                }
            }
            Text {
                color: #ffffff;
                font-family: "Source Han Sans";
                font-size: 105px;
                height: 152px;
                horizontal-alignment: center;
                text: "精算機";
                vertical-alignment: center;
                width: 429px;
                x: 297px;
                y: 27px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 43px;
                font-weight: 700;
                height: 62px;
                horizontal-alignment: center;
                text: "画面を指でタップしてください";
                vertical-alignment: center;
                width: 774px;
                x: 125px;
                y: 230px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 25px;
                height: 36px;
                horizontal-alignment: center;
                text: "Tap the screen.";
                vertical-alignment: center;
                width: 271px;
                x: 376px;
                y: 295px;
            }
            Rectangle {
                height: 61px;
                width: 366px;
                x: 40px;
                y: 376px;
                Rectangle {
                    background: #cbdfff;
                    border-radius: 18px;
                    height: 57px;
                    width: 364px;
                    x: 1px;
                    y: 2px;
                }
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 17px;
                height: 25px;
                horizontal-alignment: center;
                text: "お支払方法";
                vertical-alignment: center;
                width: 116px;
                x: 164px;
                y: 384px;
            }
            Rectangle {
                height: 162px;
                width: 947px;
                x: 38px;
                y: 408px;
                Rectangle {
                    background: #ffffff;
                    border-color: #cbdfff;
                    border-radius: 20px;
                    border-width: 4px;
                    height: 158px;
                    width: 942px;
                    x: 3px;
                    y: 2px;
                }
            }
            Image {
                height: 53px;
                image-fit: contain;
                source: @image-url("images/c65caab073f1a0d0.png");
                width: 74px;
                x: 110px;
                y: 465px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "現金";
                vertical-alignment: center;
                width: 38px;
                x: 128px;
                y: 425px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 12px;
                height: 17px;
                horizontal-alignment: center;
                text: "新紙幣も使えます";
                vertical-alignment: center;
                width: 129px;
                x: 83px;
                y: 524px;
            }
            Image {
                height: 28px;
                image-fit: contain;
                source: @image-url("images/498ce93ca6ff4e67903ef063d0f0323128da491d_1.png");
                width: 55px;
                x: 402px;
                y: 511px;
            }
            Image {
                height: 28px;
                image-fit: contain;
                source: @image-url("images/730f0f6b1a881c07b6539bb9b5886d8c8d625807_1.png");
                width: 47px;
                x: 340px;
                y: 511px;
            }
            Image {
                height: 45px;
                image-fit: contain;
                source: @image-url("images/78c7ddb491d416672ef5bb72b2851002798037cd_1.png");
                width: 58px;
                x: 270px;
                y: 502px;
            }
            Image {
                height: 44px;
                image-fit: contain;
                source: @image-url("images/05fb0171bc9c95570a5e46f62b87df372ecfe9d4_1.png");
                width: 78px;
                x: 393px;
                y: 457px;
            }
            Image {
                height: 28px;
                image-fit: contain;
                source: @image-url("images/logo_Visa_s_1.png");
                width: 72px;
                x: 264px;
                y: 465px;
            }
            Image {
                height: 32px;
                image-fit: contain;
                source: @image-url("images/8e29757faf8d84aef5487a00405801fc68e82f7f_1.png");
                width: 58px;
                x: 335px;
                y: 463px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "クレジットカード";
                vertical-alignment: center;
                width: 141px;
                x: 294px;
                y: 425px;
            }
            Image {
                height: 35px;
                image-fit: contain;
                source: @image-url("images/suica_1.png");
                width: 63px;
                x: 576px;
                y: 452px;
            }
            Image {
                height: 39px;
                image-fit: contain;
                source: @image-url("images/kitaca_1.png");
                width: 55px;
                x: 509px;
                y: 450px;
            }
            Image {
                height: 37px;
                image-fit: contain;
                source: @image-url("images/pasmo_1.png");
                width: 64px;
                x: 644px;
                y: 451px;
            }
            Image {
                height: 26px;
                image-fit: contain;
                source: @image-url("images/toica_1.png");
                width: 64px;
                x: 502px;
                y: 488px;
            }
            Image {
                height: 22px;
                image-fit: contain;
                source: @image-url("images/manaca_1.png");
                width: 76px;
                x: 568px;
                y: 492px;
            }
            Image {
                height: 32px;
                image-fit: contain;
                source: @image-url("images/icoca_1.png");
                width: 64px;
                x: 644px;
                y: 489px;
            }
            Image {
                height: 29px;
                image-fit: contain;
                source: @image-url("images/sugoca_1.png");
                width: 61px;
                x: 503px;
                y: 518px;
            }
            Image {
                height: 20px;
                image-fit: contain;
                source: @image-url("images/nimoca_1.png");
                width: 68px;
                x: 571px;
                y: 523px;
            }
            Image {
                height: 22px;
                image-fit: contain;
                source: @image-url("images/be5725fdd6cd4288.png");
                width: 64px;
                x: 644px;
                y: 523px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "交通系IC";
                vertical-alignment: center;
                width: 78px;
                x: 570px;
                y: 425px;
            }
            Image {
                height: 48px;
                image-fit: contain;
                source: @image-url("images/7c3a9aed3242d4cef15d5cece6939b528aa659c8_1.png");
                width: 84px;
                x: 878px;
                y: 477px;
            }
            Image {
                height: 32px;
                image-fit: contain;
                source: @image-url("images/88b22f4bc2aa84a66895e3451a3ab988af08a648_1.png");
                width: 55px;
                x: 814px;
                y: 485px;
            }
            Image {
                height: 33px;
                image-fit: contain;
                source: @image-url("images/eff4e4d3000699fe98a14af52a191fe59a4d7427_1.png");
                width: 59px;
                x: 742px;
                y: 485px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "電子マネー";
                vertical-alignment: center;
                width: 92px;
                x: 796px;
                y: 425px;
            }
            Rectangle {
                height: 115px;
                width: 6px;
                x: 488px;
                y: 432px;
                Rectangle {
                    background: #183e77;
                    height: 112px;
                    width: 3px;
                    x: 1px;
                    y: 1px;
                }
            }
            Rectangle {
                height: 115px;
                width: 6px;
                x: 242px;
                y: 432px;
                Rectangle {
                    background: #183e77;
                    height: 112px;
                    width: 3px;
                    x: 1px;
                    y: 1px;
                }
            }
            Rectangle {
                height: 115px;
                width: 6px;
                x: 719px;
                y: 432px;
                Rectangle {
                    background: #183e77;
                    height: 112px;
                    width: 3px;
                    x: 3px;
                    y: 1px;
                }
            }
        }
    }
}
