export component MainWindow inherits Window {
    in-out property<string> digit1-text: "2";
    in-out property<bool> digit1-visible: true;
    in-out property<string> digit10-text: "1";
    in-out property<bool> digit10-visible: true;
    in-out property<bool> footer-visible: false;
    in-out property<bool> good-bye-visible: false;
    in-out property<bool> header-visible: false;
    in-out property<bool> parking-slot-visible: false;
    in-out property<bool> payment-visible: false;
    in-out property<bool> welcome-visible: true;
    callback accept-clicked <=> accept.clicked;
    callback cancel-clicked <=> cancel.clicked;
    callback card-clicked <=> card.clicked;
    callback cash-clicked <=> cash.clicked;
    callback good-bye-clicked <=> good-bye.clicked;
    callback ic-clicked <=> ic.clicked;
    callback key-0-clicked <=> key-0.clicked;
    callback key-1-clicked <=> key-1.clicked;
    callback key-2-clicked <=> key-2.clicked;
    callback key-3-clicked <=> key-3.clicked;
    callback key-4-clicked <=> key-4.clicked;
    callback key-5-clicked <=> key-5.clicked;
    callback key-6-clicked <=> key-6.clicked;
    callback key-7-clicked <=> key-7.clicked;
    callback key-8-clicked <=> key-8.clicked;
    callback key-9-clicked <=> key-9.clicked;
    callback key-c-clicked <=> key-c.clicked;
    callback pay-clicked <=> pay.clicked;
    callback welcome-clicked <=> welcome.clicked;
    height: 600px;
    title: "";
    width: 800px;
    x: 0px;
    y: 0px;
    Rectangle {
        height: 602px;
        width: 802px;
        x: -1px;
        y: -1px;
        Rectangle {
            background: #f5f5ed;
            height: 600px;
            width: 800px;
            x: 1px;
            y: 1px;
        }
    }
    footer := Rectangle {
        visible: root.footer-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            height: 65px;
            width: 802px;
            x: -1px;
            y: 537px;
            Rectangle {
                background: #e9f1ff;
                height: 62px;
                width: 800px;
                x: 1px;
                y: 2px;
            }
        }
    }
    good-bye := TouchArea {
        visible: root.good-bye-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 43px;
                font-weight: 700;
                height: 62px;
                horizontal-alignment: center;
                text: "ご利用ありがとうございました";
                vertical-alignment: center;
                width: 610px;
                x: 94px;
                y: 239px;
            }
            Rectangle {
                height: 6px;
                width: 534px;
                x: 133px;
                y: 316px;
                Rectangle {
                    background: #183e77;
                    height: 2px;
                    width: 531px;
                    x: 1px;
                    y: 2px;
                }
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 29px;
                font-weight: 700;
                height: 84px;
                horizontal-alignment: center;
                text: "精算後5分で再びロック板が上がりますので\n５分以内に出庫してください";
                vertical-alignment: center;
                width: 602px;
                x: 100px;
                y: 354px;
            }
        }
    }
    payment := Rectangle {
        visible: root.payment-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            height: 83px;
            width: 491px;
            x: 176px;
            y: 99px;
            Rectangle {
                background: #ffffff;
                height: 80px;
                width: 488px;
                x: 1px;
                y: 2px;
            }
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 35px;
            font-weight: 700;
            height: 51px;
            horizontal-alignment: left;
            text: "料金は";
            vertical-alignment: center;
            width: 110px;
            x: 49px;
            y: 126px;
        }
        amount := Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 49px;
            font-weight: 700;
            height: 71px;
            horizontal-alignment: left;
            text: "200";
            vertical-alignment: center;
            visible: true;
            width: 96px;
            x: 373px;
            y: 103px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 27px;
            font-weight: 700;
            height: 39px;
            horizontal-alignment: left;
            text: "円";
            vertical-alignment: center;
            width: 27px;
            x: 612px;
            y: 137px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 35px;
            font-weight: 700;
            height: 51px;
            horizontal-alignment: left;
            text: "です";
            vertical-alignment: center;
            width: 71px;
            x: 682px;
            y: 126px;
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 28px;
            font-weight: 700;
            height: 40px;
            horizontal-alignment: left;
            text: "お支払方法をお選びください";
            vertical-alignment: center;
            width: 384px;
            x: 208px;
            y: 223px;
        }
        cash := TouchArea {
            height: 91px;
            visible: true;
            width: 315px;
            x: 76px;
            y: 293px;
            Rectangle {
                height: 91px;
                width: 315px;
                x: cash.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(180.000deg, #ffeec1 0%, #ffbb04 33.4717%, #e98900 99.4385%);
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #3b202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 88px;
                    width: 312px;
                    x: 2px;
                    y: 1px;
                }
            }
        }
        card := TouchArea {
            height: 91px;
            visible: true;
            width: 315px;
            x: 408px;
            y: 293px;
            Rectangle {
                height: 91px;
                width: 315px;
                x: card.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(180.000deg, #ffeec1 0%, #ffbb04 33.4717%, #e98900 99.4385%);
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #3b202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 88px;
                    width: 312px;
                    x: 2px;
                    y: 1px;
                }
            }
        }
        ic := TouchArea {
            height: 91px;
            visible: true;
            width: 315px;
            x: 76px;
            y: 401px;
            Rectangle {
                height: 91px;
                width: 315px;
                x: ic.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(180.000deg, #ffeec1 0%, #ffbb04 33.4717%, #e98900 99.4385%);
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #3b202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 88px;
                    width: 312px;
                    x: 2px;
                    y: 1px;
                }
            }
        }
        pay := TouchArea {
            height: 91px;
            visible: true;
            width: 315px;
            x: 408px;
            y: 401px;
            Rectangle {
                height: 91px;
                width: 315px;
                x: pay.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(180.000deg, #ffeec1 0%, #ffbb04 33.4717%, #e98900 99.4385%);
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #3b202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 88px;
                    width: 312px;
                    x: 2px;
                    y: 1px;
                }
            }
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 25px;
            font-weight: 700;
            height: 36px;
            horizontal-alignment: left;
            text: "サービス券は先に入れてください";
            vertical-alignment: center;
            width: 389px;
            x: 206px;
            y: 551px;
        }
    }
    parking-slot := Rectangle {
        visible: root.parking-slot-visible;
        x: 0px;
        y: 0px;
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 35px;
            font-weight: 700;
            height: 51px;
            horizontal-alignment: center;
            text: "駐車位置番号を入力してください";
            vertical-alignment: center;
            width: 543px;
            x: 129px;
            y: 113px;
        }
        key-1 := TouchArea {
            height: 50px;
            visible: true;
            width: 88px;
            x: 431px;
            y: 204px;
            Rectangle {
                height: 50px;
                width: 88px;
                x: key-1.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
        key-2 := TouchArea {
            height: 50px;
            visible: true;
            width: 88px;
            x: 531px;
            y: 204px;
            Rectangle {
                height: 50px;
                width: 88px;
                x: key-2.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 2px;
                    y: 2px;
                }
            }
        }
        key-3 := TouchArea {
            height: 50px;
            visible: true;
            width: 88px;
            x: 633px;
            y: 204px;
            Rectangle {
                height: 50px;
                width: 88px;
                x: key-3.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
        key-4 := TouchArea {
            height: 49px;
            visible: true;
            width: 88px;
            x: 431px;
            y: 266px;
            Rectangle {
                height: 49px;
                width: 88px;
                x: key-4.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
        key-5 := TouchArea {
            height: 49px;
            visible: true;
            width: 88px;
            x: 531px;
            y: 266px;
            Rectangle {
                height: 49px;
                width: 88px;
                x: key-5.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 2px;
                    y: 2px;
                }
            }
        }
        key-6 := TouchArea {
            height: 49px;
            visible: true;
            width: 88px;
            x: 633px;
            y: 266px;
            Rectangle {
                height: 49px;
                width: 88px;
                x: key-6.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
        key-7 := TouchArea {
            height: 48px;
            visible: true;
            width: 88px;
            x: 431px;
            y: 329px;
            Rectangle {
                height: 48px;
                width: 88px;
                x: key-7.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 1px;
                }
            }
        }
        key-8 := TouchArea {
            height: 48px;
            visible: true;
            width: 88px;
            x: 531px;
            y: 329px;
            Rectangle {
                height: 48px;
                width: 88px;
                x: key-8.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 2px;
                    y: 1px;
                }
            }
        }
        key-9 := TouchArea {
            height: 48px;
            visible: true;
            width: 88px;
            x: 633px;
            y: 329px;
            Rectangle {
                height: 48px;
                width: 88px;
                x: key-9.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 1px;
                }
            }
        }
        key-0 := TouchArea {
            height: 50px;
            visible: true;
            width: 88px;
            x: 531px;
            y: 390px;
            Rectangle {
                height: 50px;
                width: 88px;
                x: key-0.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 2px;
                    y: 2px;
                }
            }
        }
        key-c := TouchArea {
            height: 50px;
            visible: true;
            width: 88px;
            x: 633px;
            y: 390px;
            Rectangle {
                height: 50px;
                width: 88px;
                x: key-c.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(0.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #52202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 85px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
        Rectangle {
            height: 232px;
            width: 358px;
            x: 43px;
            y: 206px;
            Rectangle {
                background: #ffffff;
                border-color: #6f6f6f;
                border-radius: 20px;
                border-width: 6px;
                height: 230px;
                width: 356px;
                x: 1px;
                y: 1px;
            }
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 24px;
            height: 35px;
            horizontal-alignment: center;
            text: "NO.";
            vertical-alignment: center;
            width: 47px;
            x: 107px;
            y: 327px;
        }
        Rectangle {
            height: 90px;
            width: 71px;
            x: 175px;
            y: 277px;
            Rectangle {
                background: #ffffff;
                border-color: #000000;
                border-width: 1px;
                height: 87px;
                width: 68px;
                x: 1px;
                y: 1px;
            }
        }
        digit10 := Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 46px;
            height: 66px;
            horizontal-alignment: center;
            text: root.digit10-text;
            vertical-alignment: center;
            visible: root.digit10-visible;
            width: 26px;
            x: 197px;
            y: 286px;
        }
        Rectangle {
            height: 90px;
            width: 71px;
            x: 265px;
            y: 277px;
            Rectangle {
                background: #ffffff;
                border-color: #000000;
                border-width: 1px;
                height: 87px;
                width: 68px;
                x: 2px;
                y: 1px;
            }
        }
        digit1 := Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 46px;
            height: 66px;
            horizontal-alignment: center;
            text: root.digit1-text;
            vertical-alignment: center;
            visible: root.digit1-visible;
            width: 26px;
            x: 288px;
            y: 286px;
        }
        accept := TouchArea {
            height: 50px;
            visible: true;
            width: 358px;
            x: 43px;
            y: 459px;
            Rectangle {
                height: 50px;
                width: 358px;
                x: accept.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(180.000deg, #ffeec1 0%, #ffbb04 33.4717%, #e98900 99.4385%);
                    drop-shadow-blur: 6px;
                    drop-shadow-color: #3b202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 356px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
    }
    header := Rectangle {
        visible: root.header-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            height: 156px;
            width: 885px;
            x: -57px;
            y: -78px;
            Rectangle {
                background: #183e77;
                height: 154px;
                width: 882px;
                x: 1px;
                y: 1px;
            }
        }
        cancel := TouchArea {
            height: 50px;
            visible: true;
            width: 128px;
            x: 31px;
            y: 13px;
            Rectangle {
                height: 50px;
                width: 128px;
                x: cancel.pressed ? 2px : 0px;
                y: self.x;
                Rectangle {
                    background: @linear-gradient(360.000deg, #dadada 0%, #ffffff 100%);
                    border-radius: 6px;
                    drop-shadow-blur: 10px;
                    drop-shadow-color: #a6202020;
                    drop-shadow-offset-x: 3px;
                    drop-shadow-offset-y: 3px;
                    height: 46px;
                    width: 125px;
                    x: 1px;
                    y: 2px;
                }
            }
        }
        Rectangle {
            height: 50px;
            width: 128px;
            x: 641px;
            y: 13px;
            Rectangle {
                background: @linear-gradient(360.000deg, #dadada 0%, #ffffff 100%);
                border-radius: 6px;
                drop-shadow-blur: 10px;
                drop-shadow-color: #a6202020;
                drop-shadow-offset-x: 3px;
                drop-shadow-offset-y: 3px;
                height: 46px;
                width: 125px;
                x: 2px;
                y: 2px;
            }
        }
        Text {
            color: #000000;
            font-family: "Source Han Sans";
            font-size: 17px;
            height: 25px;
            horizontal-alignment: center;
            text: "English";
            vertical-alignment: center;
            width: 66px;
            x: 671px;
            y: 24px;
        }
        Text {
            color: #ffffff;
            font-family: "Source Han Sans";
            font-size: 30px;
            font-weight: 700;
            height: 44px;
            horizontal-alignment: center;
            text: "12：24";
            vertical-alignment: center;
            width: 100px;
            x: 500px;
            y: 14px;
        }
    }
    welcome := TouchArea {
        visible: root.welcome-visible;
        x: 0px;
        y: 0px;
        Rectangle {
            Rectangle {
                height: 157px;
                width: 738px;
                x: 31px;
                y: 31px;
                Rectangle {
                    background: #183e77;
                    height: 154px;
                    width: 736px;
                    x: 1px;
                    y: 1px;
                }
            }
            Text {
                color: #ffffff;
                font-family: "Source Han Sans";
                font-size: 105px;
                height: 152px;
                horizontal-alignment: center;
                text: "精算機";
                vertical-alignment: center;
                width: 335px;
                x: 232px;
                y: 27px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 43px;
                font-weight: 700;
                height: 62px;
                horizontal-alignment: center;
                text: "画面を指でタップしてください";
                vertical-alignment: center;
                width: 605px;
                x: 98px;
                y: 230px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 25px;
                height: 36px;
                horizontal-alignment: center;
                text: "Tap the screen.";
                vertical-alignment: center;
                width: 212px;
                x: 294px;
                y: 295px;
            }
            Rectangle {
                height: 61px;
                width: 286px;
                x: 31px;
                y: 376px;
                Rectangle {
                    background: #cbdfff;
                    border-radius: 14px;
                    height: 57px;
                    width: 284px;
                    x: 1px;
                    y: 2px;
                }
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 17px;
                height: 25px;
                horizontal-alignment: center;
                text: "お支払方法";
                vertical-alignment: center;
                width: 91px;
                x: 128px;
                y: 384px;
            }
            Rectangle {
                height: 162px;
                width: 740px;
                x: 30px;
                y: 408px;
                Rectangle {
                    background: #ffffff;
                    border-color: #cbdfff;
                    border-radius: 16px;
                    border-width: 4px;
                    height: 158px;
                    width: 736px;
                    x: 2px;
                    y: 2px;
                }
            }
            Image {
                height: 53px;
                image-fit: contain;
                source: @image-url("images/c65caab073f1a0d0.png");
                width: 58px;
                x: 86px;
                y: 465px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "現金";
                vertical-alignment: center;
                width: 30px;
                x: 100px;
                y: 425px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 12px;
                height: 17px;
                horizontal-alignment: center;
                text: "新紙幣も使えます";
                vertical-alignment: center;
                width: 101px;
                x: 65px;
                y: 524px;
            }
            Image {
                height: 28px;
                image-fit: contain;
                source: @image-url("images/498ce93ca6ff4e67903ef063d0f0323128da491d.png");
                width: 43px;
                x: 314px;
                y: 511px;
            }
            Image {
                height: 28px;
                image-fit: contain;
                source: @image-url("images/730f0f6b1a881c07b6539bb9b5886d8c8d625807.png");
                width: 37px;
                x: 266px;
                y: 511px;
            }
            Image {
                height: 45px;
                image-fit: contain;
                source: @image-url("images/78c7ddb491d416672ef5bb72b2851002798037cd.png");
                width: 45px;
                x: 211px;
                y: 502px;
            }
            Image {
                height: 44px;
                image-fit: contain;
                source: @image-url("images/05fb0171bc9c95570a5e46f62b87df372ecfe9d4.png");
                width: 61px;
                x: 307px;
                y: 457px;
            }
            Image {
                height: 28px;
                image-fit: contain;
                source: @image-url("images/logo_Visa_s.png");
                width: 56px;
                x: 206px;
                y: 465px;
            }
            Image {
                height: 32px;
                image-fit: contain;
                source: @image-url("images/8e29757faf8d84aef5487a00405801fc68e82f7f.png");
                width: 45px;
                x: 262px;
                y: 463px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "クレジットカード";
                vertical-alignment: center;
                width: 110px;
                x: 230px;
                y: 425px;
            }
            Image {
                height: 35px;
                image-fit: contain;
                source: @image-url("images/suica.png");
                width: 49px;
                x: 450px;
                y: 452px;
            }
            Image {
                height: 39px;
                image-fit: contain;
                source: @image-url("images/kitaca.png");
                width: 43px;
                x: 398px;
                y: 450px;
            }
            Image {
                height: 37px;
                image-fit: contain;
                source: @image-url("images/pasmo.png");
                width: 50px;
                x: 503px;
                y: 451px;
            }
            Image {
                height: 26px;
                image-fit: contain;
                source: @image-url("images/toica.png");
                width: 50px;
                x: 392px;
                y: 488px;
            }
            Image {
                height: 22px;
                image-fit: contain;
                source: @image-url("images/manaca.png");
                width: 59px;
                x: 444px;
                y: 492px;
            }
            Image {
                height: 32px;
                image-fit: contain;
                source: @image-url("images/icoca.png");
                width: 50px;
                x: 503px;
                y: 489px;
            }
            Image {
                height: 29px;
                image-fit: contain;
                source: @image-url("images/sugoca.png");
                width: 48px;
                x: 393px;
                y: 518px;
            }
            Image {
                height: 20px;
                image-fit: contain;
                source: @image-url("images/nimoca.png");
                width: 53px;
                x: 446px;
                y: 523px;
            }
            Image {
                height: 22px;
                image-fit: contain;
                source: @image-url("images/be5725fdd6cd4288.png");
                width: 50px;
                x: 503px;
                y: 523px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "交通系IC";
                vertical-alignment: center;
                width: 61px;
                x: 445px;
                y: 425px;
            }
            Image {
                height: 48px;
                image-fit: contain;
                source: @image-url("images/7c3a9aed3242d4cef15d5cece6939b528aa659c8.png");
                width: 66px;
                x: 686px;
                y: 477px;
            }
            Image {
                height: 32px;
                image-fit: contain;
                source: @image-url("images/88b22f4bc2aa84a66895e3451a3ab988af08a648.png");
                width: 43px;
                x: 636px;
                y: 485px;
            }
            Image {
                height: 33px;
                image-fit: contain;
                source: @image-url("images/eff4e4d3000699fe98a14af52a191fe59a4d7427.png");
                width: 46px;
                x: 580px;
                y: 485px;
            }
            Text {
                color: #000000;
                font-family: "Source Han Sans";
                font-size: 14px;
                height: 20px;
                horizontal-alignment: center;
                text: "電子マネー";
                vertical-alignment: center;
                width: 72px;
                x: 622px;
                y: 425px;
            }
            Rectangle {
                height: 115px;
                width: 5px;
                x: 381px;
                y: 432px;
                Rectangle {
                    background: #183e77;
                    height: 112px;
                    width: 2px;
                    x: 1px;
                    y: 1px;
                }
            }
            Rectangle {
                height: 115px;
                width: 5px;
                x: 189px;
                y: 432px;
                Rectangle {
                    background: #183e77;
                    height: 112px;
                    width: 2px;
                    x: 1px;
                    y: 1px;
                }
            }
            Rectangle {
                height: 115px;
                width: 5px;
                x: 562px;
                y: 432px;
                Rectangle {
                    background: #183e77;
                    height: 112px;
                    width: 2px;
                    x: 2px;
                    y: 1px;
                }
            }
        }
    }
}
